// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

uint Resolution;
RWTexture2D<float> Result;

void SetResult(uint3 id, float value)
{
    if (id.x < Resolution && id.y < Resolution)
    {
        Result[id.xy] = value;
    }
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    SetResult(id, (sin(id.x * 0.1) + cos(id.y * 0.1)) / 4.0 + 0.5);
}